    const data = [
      { name: "Blocky Browser", url: "services/browser", query: "internet" },
      { name: "Blocky Browser", url: "services/browser", query: "internet browser" },
      { name: "Blocky Browser", url: "services/browser", query: "browser" },
      { name: "Blocky Browser", url: "services/browser", query: "blocky browser" },

      { name: "Retro Bowl", url: "retro-bowl", query: "retro bowl" },
      { name: "Retro Bowl", url: "retro-bowl", query: "retro bowl college" },

      { name: "Snow Rider 3D", url: "snow-rider-3d", query: "snow rider 3d" },
      { name: "Snow Rider 3D", url: "snow-rider-3d", query: "snow rider" },

      { name: "Balloons TD 1", url: "balloons-td-1", query: "balloons td" },
      { name: "Balloons TD 2", url: "balloons-td-2", query: "balloons td" },
      { name: "Balloons TD 3", url: "balloons-td-3", query: "balloons td" },
      { name: "Balloons TD 4", url: "balloons-td-4", query: "balloons td" },
      { name: "Balloons TD 4 expansion", url: "balloons-td-4e", query: "balloons td" },
      { name: "Balloons TD 5", url: "balloons-td-5", query: "balloons td" },
      { name: "Balloons TD 1", url: "balloons-td-1", query: "balloons td 1" },
      { name: "Balloons TD 2", url: "balloons-td-2", query: "balloons td 2" },
      { name: "Balloons TD 3", url: "balloons-td-3", query: "balloons td 3" },
      { name: "Balloons TD 4", url: "balloons-td-4", query: "balloons td 4" },
      { name: "Balloons TD 4 expansion", url: "balloons-td-4e", query: "balloons td 4 expansion" },
      { name: "Balloons TD 4 expansion", url: "balloons-td-4e", query: "balloons td 4e" },
      { name: "Balloons TD 5", url: "balloons-td-5", query: "balloons td 5" },
      { name: "Balloons TD 1", url: "balloons-td-1", query: "balloons tower defense" },
      { name: "Balloons TD 2", url: "balloons-td-2", query: "balloons tower defense" },
      { name: "Balloons TD 3", url: "balloons-td-3", query: "balloons tower defense" },
      { name: "Balloons TD 4", url: "balloons-td-4", query: "balloons tower defense" },
      { name: "Balloons TD 4 expansion", url: "balloons-td-4e", query: "balloons tower defense" },
      { name: "Balloons TD 5", url: "balloons-td-5", query: "balloons tower defense" },
      { name: "Balloons TD 1", url: "balloons-td-1", query: "balloons tower defense 1" },
      { name: "Balloons TD 2", url: "balloons-td-2", query: "balloons tower defense 2" },
      { name: "Balloons TD 3", url: "balloons-td-3", query: "balloons tower defense 3" },
      { name: "Balloons TD 4", url: "balloons-td-4", query: "balloons tower defense 4" },
      { name: "Balloons TD 4 expansion", url: "balloons-td-4e", query: "balloons tower defense 4 expansion" },
      { name: "Balloons TD 4 expansion", url: "balloons-td-4e", query: "balloons tower defense 4e" },
      { name: "Balloons TD 5", url: "balloons-td-5", query: "balloons tower defense 5" },

      { name: "Duck Life 1", url: "duck-life-1", query: "duck life" },
      { name: "Duck Life 2", url: "duck-life-2", query: "duck life" },
      { name: "Duck Life 3", url: "duck-life-3", query: "duck life" },
      { name: "Duck Life 4", url: "duck-life-4", query: "duck life" },
      { name: "Duck Life 1", url: "duck-life-1", query: "duck life 1" },
      { name: "Duck Life 2", url: "duck-life-2", query: "duck life 2" },
      { name: "Duck Life 3", url: "duck-life-3", query: "duck life 3" },
      { name: "Duck Life 4", url: "duck-life-4", query: "duck life 4" },

      { name: "Super Mario bros.", url: "super-mario", query: "mario" },
      { name: "Super Mario bros.", url: "super-mario", query: "super mario" },
      { name: "Super Mario bros.", url: "super-mario", query: "super mario bros" },
      { name: "Super Mario bros.", url: "super-mario", query: "super mario brothers" },
      
      { name: "Granny", url: "granny", query: "granny" },
        
      { name: "Moto Road Rash 3D", url: "moto-road-rash-3d", query: "moto rush" },
      { name: "Moto Road Rash 3D", url: "moto-road-rash-3d", query: "moto rush 3d" },
      { name: "Moto Road Rash 3D", url: "moto-road-rash-3d", query: "moto road rash 3d" },
      { name: "Moto Road Rash 3D", url: "moto-road-rash-3d", query: "moto road rash" },
      { name: "Moto Road Rash 3D", url: "moto-road-rash-3d", query: "moto road rush 3d" },
      { name: "Moto Road Rash 3D", url: "moto-road-rash-3d", query: "moto road rush" },
      { name: "Moto Road Rash 3D", url: "moto-road-rash-3d", query: "motorcycle game" },
      { name: "Moto Road Rash 3D", url: "moto-road-rash-3d", query: "motorcycle" },

      { name: "Temple Run 2", url: "temple-run-2", query: "temple run" },
      { name: "Temple Run 2", url: "temple-run-2", query: "temple run 2" },
      { name: "Temple Run 2", url: "temple-run-2", query: "temple" },
      { name: "Temple Run 2", url: "temple-run-2", query: "temple rush" },

      { name: "Tunnel Rush", url: "tunnel-rush", query: "tunnel rush" },

      { name: "Subway Surfers", url: "subway-surfers", query: "subway surfers" },
      { name: "Subway Surfers", url: "subway-surfers", query: "subway surf" },
      { name: "Subway Surfers", url: "subway-surfers", query: "subway surfer" },

      // audio services
      { name: "Audio Services", url: "services", query: "audio services" },
      { name: "Audio Services", url: "services", query: "audio" },
      { name: "Audio Services", url: "services", query: "music services" },
      { name: "Audio Services", url: "services", query: "music" },
      { name: "Audio Services", url: "services", query: "audio converter" },
      { name: "Audio Service", url: "services", query: "mp3" },
      { name: "Audio Service", url: "services", query: "converter" },
      { name: "Audio Service", url: "services", query: "convert" },

      { name: "Audio Service", url: "services", query: "bass boost" },
      { name: "Audio Service", url: "services", query: "bass booster" },
      { name: "Audio Service", url: "services", query: "audio boost" },
      { name: "Audio Service", url: "services", query: "audio booster" },
      { name: "Audio Service", url: "services", query: "music boost" },
      { name: "Audio Service", url: "services", query: "music booster" },
      { name: "Audio Service", url: "services", query: "audio bass boost" },
      { name: "Audio Service", url: "services", query: "audio bass booster" },
      { name: "Audio Service", url: "services", query: "music bass boost" },
      { name: "Audio Service", url: "services", query: "music bass booster" },
      { name: "Audio Service", url: "services", query: "mp3 bass boost" },
      { name: "Audio Service", url: "services", query: "mp3 bass booster" },
      { name: "Audio Service", url: "services", query: ".mp3 bass boost" },
      { name: "Audio Service", url: "services", query: ".mp3 bass booster" },
      { name: "Audio Service", url: "services", query: "mpeg bass boost" },
      { name: "Audio Service", url: "services", query: "mpeg bass booster" },
      { name: "Audio Service", url: "services", query: "mp4 bass boost" },
      { name: "Audio Service", url: "services", query: "mp4 bass booster" },
      { name: "Audio Service", url: "services", query: ".mp4 bass boost" },
      { name: "Audio Service", url: "services", query: ".mp4 bass booster" },
      { name: "Audio Service", url: "services", query: "mpeg video bass booster" },
      { name: "Audio Service", url: "services", query: "mpeg video bass boost" },
      { name: "Audio Service", url: "services", query: "m4a bass boost" },
      { name: "Audio Service", url: "services", query: "m4a bass booster" },
      { name: "Audio Service", url: "services", query: ".m4a bass boost" },
      { name: "Audio Service", url: "services", query: ".m4a bass booster" },

      { name: "Audio Service", url: "services", query: "youtube" },
      { name: "Audio Service", url: "services", query: "youtube to mp3" },
      { name: "Audio Service", url: "services", query: "youtube download" },
      { name: "Audio Service", url: "services", query: "yt" },
      { name: "Audio Service", url: "services", query: "yt mp3" },
      { name: "Audio Service", url: "services", query: "yt download" },
      { name: "Audio Service", url: "services", query: "youtube" },

      { name: "Audio Service", url: "services", query: "mp3 to wav" },
      { name: "Audio Service", url: "services", query: "wav" },
    ];
